platform :ios, "8.0"
use_frameworks!
target 'Snapcard' do
    pod 'AFNetworking', '~> 3.0'
    pod 'ChameleonFramework'
    pod 'JVFloatLabeledTextField'
    pod 'FontAwesomeKit', '~> 2.2.0'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'PPiFlatSegmentedControl'
    pod 'PulsingHalo'
    pod 'TWMessageBarManager'
    pod 'DZNEmptyDataSet'
end

